sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose up -d

python:
    - "2.7"

install:
  - pip install pytest
  - pip install requests
  
script:
  - py.test -v -l
  