sudo: required

language: python

services:
  - docker

before_install:
  - docker build --tag simple_python_rest_api_v2 .
  - docker run -p 127.0.0.1:5002:5002 -d simple_python_rest_api_v2
  
python:
    - "2.7"

install:
  - pip install pytest
  - pip install requests
  
script:
  - py.test -v -l
  