version: '3'

services:   
  mariadb-service:
    image:  mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=titanic
      - MYSQL_USER=restuser
      - MYSQL_PASSWORD=restpassword
     
  normalize-db-service:
    build: ./normalize-db
    volumes:
      - ./normalize-db:/app-db/
    depends_on:
      - mariadb-service

  rest-api-service:
    build: ./app
    volumes:
      - ./app:/app
    # ports:
    #   - 5002:5002
    depends_on:
      - normalize-db-service
      